# Generated by Django 4.1.2 on 2022-10-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256, null=True)),
                ('category', models.CharField(choices=[('MT', 'Masa Takımı'), ('M', 'Masa'), ('S', 'Sandalye'), ('OS', 'Orta Sehpa'), ('OS', 'Servis Sehpası'), ('SS', 'Set Sehpa')], max_length=6, null=True)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
