# Generated by Django 4.1.2 on 2022-10-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MT', 'Masa Takımı'), ('M', 'Masa'), ('S', 'Sandalye'), ('OS', 'Orta Sehpa'), ('YS', 'Yan Sehpa'), ('SES', 'Servis Sehpası'), ('SS', 'Set Sehpa'), ('P', 'Puf')], max_length=6, null=True),
        ),
    ]
