# Generated by Django 4.1.2 on 2022-10-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_sliderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product/image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MT', 'Masa Takımı'), ('M', 'Masa'), ('S', 'Sandalye'), ('OS', 'Orta Sehpa'), ('YS', 'Yan Sehpa'), ('SES', 'Servis Sehpası'), ('SS', 'Set Sehpa'), ('P', 'Puf')], max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
