# Generated by Django 4.1.2 on 2022-10-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MasaT', 'Masa Takımı'), ('Masa', 'Masa'), ('OrtaS', 'Orta Sehpa'), ('YanS', 'Yan Sehpa'), ('ServisS', 'Servis Sehpası'), ('SetS', 'Set Sehpa'), ('Puf', 'Puf')], max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_tr',
            field=models.TextField(null=True),
        ),
    ]
