# Generated by Django 4.1.2 on 2022-10-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MasaT', 'Masa Takımı'), ('Masa', 'Masa'), ('Sandalye', 'Sandalye'), ('OrtaS', 'Orta Sehpa'), ('YanS', 'Yan Sehpa'), ('ServisS', 'Servis Sehpası'), ('SetS', 'Set Sehpa'), ('Puf', 'Puf')], max_length=8),
        ),
    ]
