# Generated by Django 4.1.2 on 2022-11-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cateagory',
            field=models.CharField(blank=True, choices=[('MasaT', 'Masa Takımı'), ('Masa', 'Masa'), ('Sandalye', 'Sandalye'), ('OrtaS', 'Orta Sehpa'), ('YanS', 'Yan Sehpa'), ('ServisS', 'Servis Sehpası'), ('SetS', 'Set Sehpa'), ('Puf', 'Puf')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
