# Generated by Django 4.1.2 on 2022-11-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_cateagory_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categorya',
        ),
    ]
