# Generated by Django 4.1.2 on 2022-11-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_rename_category_product_categorya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cateagory',
            new_name='category',
        ),
    ]
