# Generated by Django 4.1.2 on 2022-11-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_rename_cateagory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorya',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
