# Generated by Django 4.1.2 on 2022-11-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_category_slug_category_slug_en_category_slug_tr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_tr',
        ),
    ]
