# Generated by Django 4.1.2 on 2022-11-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_category_slug_en_remove_category_slug_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_tr',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
