# Generated by Django 4.1.2 on 2022-11-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_categoryproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
