# Generated by Django 4.1.2 on 2022-11-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_categoryproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='description_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='description_tr',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
