# Generated by Django 4.1.2 on 2022-10-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_product', to='product.product')),
            ],
        ),
    ]
