# Generated by Django 4.1.2 on 2022-11-07 10:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='fairs/image/%Y/%m/%d/')),
                ('date', models.DateField(null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FairImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fair/images/%Y/%m/%d/')),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_image', to='pages.fair')),
            ],
        ),
    ]
