# Generated by Django 4.1.2 on 2022-11-07 10:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_fair_fairimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fair',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fair',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='fair',
            name='name_tr',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
